# Generated by Django 4.2.9 on 2024-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('contact_person_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('company_address', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('industry_type', models.CharField(max_length=50)),
                ('company_size', models.IntegerField()),
                ('company_description', models.TextField()),
                ('website_url', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('industry_certification', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=50)),
                ('terms_conditions_accepted', models.BooleanField()),
                ('captcha_verified', models.BooleanField()),
                ('social_media_links', models.CharField(blank=True, max_length=200)),
                ('additional_contact_info', models.CharField(blank=True, max_length=200)),
                ('receive_notifications', models.BooleanField(default=False)),
                ('agreement_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
