# Generated by Django 4.2.9 on 2024-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('zip_postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('manager_supervisor_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('ssn_or_national_id', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('relationship_to_employee', models.CharField(max_length=50)),
                ('emergency_contact_phone_number', models.CharField(max_length=15)),
                ('tax_filing_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('withholding_allowances', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(max_length=50)),
                ('health_insurance_enrollment', models.BooleanField(default=False)),
                ('retirement_plan_enrollment', models.BooleanField(default=False)),
                ('education_level', models.CharField(max_length=100)),
                ('degrees_certifications', models.CharField(max_length=200)),
                ('skills_expertise', models.TextField()),
                ('preferred_language', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=50)),
                ('terms_conditions_accepted', models.BooleanField()),
                ('captcha_verified', models.BooleanField()),
                ('ethnicity', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('asian', 'Asian'), ('hispanic', 'Hispanic'), ('other', 'Other')], max_length=20)),
                ('disability_status', models.BooleanField(default=False)),
                ('veteran_status', models.BooleanField(default=False)),
                ('receive_notifications', models.BooleanField(default=False)),
                ('agreement_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
